Updating the CI/CD workflows based on the workflows from the OSCAL repo.

diff --git a/.github/workflows/workflow-validate-repo-markdown.yml b/.github/workflows/workflow-validate-repo-markdown.yml
--- a/.github/workflows/workflow-validate-repo-markdown.yml
+++ b/.github/workflows/workflow-validate-repo-markdown.yml
@@ -1,4 +1,4 @@
-name: Metaschema Validate Repo Markdown
+name: Validate Repo Markdown
 on:
   workflow_call:
     inputs:
@@ -12,31 +12,24 @@ on:
         required: false
         default: 'build/config/.markdown-link-check/config.json'
         type: string
-  workflow_dispatch:
-    inputs:
-      ignorePattern:
-        description: 'a pattern provided to grep for files/directories to ignore'
+      create_issue:
+        description: 'create new GitHub issue if broken links found'
         required: false
-        default: '^website/'
-        type: string
-      markdownLinkCheckConfig:
-        description: 'the path to the markdown link check config file'
-        required: false
-        default: 'build/config/.markdown-link-check/config.json'
-        type: string
+        default: false
+        type: boolean
 jobs:
   validate-repo-markdown:
     name: Validate Repo Markdown
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     steps:
     # use this for pulls where checkout is anonymous
-    - uses: actions/checkout@v3 # current: dcd71f646680f2efd8db4afa5ad64fdcba30e748
+    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
       with:
         submodules: recursive
     # Setup runtime environment
     # -------------------------
     - name: Set up NodeJS
-      uses: actions/setup-node@v3 # current: 56337c425554a6be30cdef71bf441f15be286854 
+      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
       with:
         node-version-file: 'build/.nvmrc'
         cache: 'npm'
@@ -45,6 +38,13 @@ jobs:
       run: |
         # NodeJS
         cd "${{ github.workspace }}/build"
+        # If you are a developer and need to modify the workflow, be sure to review
+        # the package.json and package-lock.json to ensure the following deps are
+        # at least installed (they will be updated by dependabot):
+        # - ajv-cli
+        # - ajv-formats
+        # - markdown-link-check
+        # - yaml-convert
         npm install --loglevel verbose
         echo "$PWD/node_modules/.bin/" >> $GITHUB_PATH
     # Build Artifacts
@@ -52,4 +52,19 @@ jobs:
     - name: Validate repo Markdown content instances
       run: |
         # this command will filter out any docs Markdown files, which are checked in a different job
-        git ls-files "*/*.md" -z | grep --null-data -v "${{ inputs.ignorePattern }}" | xargs -0 -n1 markdown-link-check -q -c "${{ inputs.markdownLinkCheckConfig }}"
+        git ls-files "*.md" -z | \
+        grep --null-data -v "${{ inputs.ignorePattern }}" | \
+        xargs -0 markdown-link-check -c "${{ inputs.markdownLinkCheckConfig }}" | \
+        tee mlc_report.log
+        # Exit code of xargs and markdown-link-check, not git or grep or tee pipe elements
+        exit ${PIPESTATUS[2]}
+      id: linkchecker
+    - name: Create issue if bad links detected in repo
+      if: failure() && inputs.create_issue == true
+      uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v3.0.0
+      with:
+        title: Scheduled Check of Markdown Documents Found Bad Hyperlinks
+        content-filepath: mlc_report.log
+        labels: |
+          bug
+          Scope: Documentation
